name: 11ty Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # concurrency: ci-${{github.ref}}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Build
    #   run: dotnet build ./Unity-Performance-Field-Guide.csproj --configuration Release --no-restore
    - name: Run
      run: npx @11ty/eleventy --formats=html,gif,png,jpeg,mp3,liquid,md,css,toml --input=src --output=_site

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
        branch: gh-pages