name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore --project Unity-Performance-Field-Guide.csproj
    - name: Build
      run: dotnet build --project Unity-Performance-Field-Guide.csproj -configuration Release -no-restore
